## Set of array-construction exercises in NumPY
This notebook shows my solutions to array-construction exercises in NumPy.  
Markdown cells show the target matrices; code cells show my solution.

Constraints: 
- no for loops,
- only NumPy functions (zeros, ones, eye, diag, arange, reshape, linspace, slicing, indexing, ...)



In [32]:
import numpy as np

#### Target 01
```
[[1 2 3 4 5 6]]

In [33]:
import numpy as np
a=np.arange(1,7)
print(a)

[1 2 3 4 5 6]


#### Target 02
```
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

In [34]:
b=np.arange(1,7)
b=b.reshape(-1,1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### Target 03
```
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]

In [35]:
c=np.eye(5,k=1)
print(c)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


#### Target 04
```
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

In [36]:
d = np.diag((1,2,3,4))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### Target 05
```
[[0 0 0 1]
 [0 0 2 0]
 [0 3 0 0]
 [4 0 0 0]]

In [37]:
e=np.zeros((4,4))
for i in range(4):
    e[i,3-i]=i+1
print(e)

[[0. 0. 0. 1.]
 [0. 0. 2. 0.]
 [0. 3. 0. 0.]
 [4. 0. 0. 0.]]


#### Target 06
```
[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]

In [38]:
f = np.zeros((6,6))
f[0::2, 1::2]=1
f[1::2, 0::2]=1
print(f)

[[0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]]


#### Target 07
```
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]

In [39]:
g = np.zeros((5,5))
for i in range(g.shape[0]):
    g[i::]=i
print(g)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### Target 08
```
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

In [40]:
h = np.zeros((5,5))
for i in range(h.shape[0]):
    h[:,i::] = i
print(h)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### Target 09
```
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [41]:
j = np.arange (10,25)
j = np.reshape(j,(3,5))
print(j)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Target 10
```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

In [42]:
k = np.arange (0,18)
k= np.reshape (k, (3,6))
print(k)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


#### Target 11
```
[[ 0  6 12]
 [ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]]

In [43]:
l = np.zeros ((6,3))
l[:,0] = range(0,6)
l[:,1] = range(6,12)
l[:,2] = range(12,18)
print(l)

[[ 0.  6. 12.]
 [ 1.  7. 13.]
 [ 2.  8. 14.]
 [ 3.  9. 15.]
 [ 4. 10. 16.]
 [ 5. 11. 17.]]


#### Target 12
```
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

In [44]:
m = np.zeros ((5,5))
m[0,:]=1
m[4,:]=1
m[:,0]=1
m[:,4]=1
print(m)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Target 13
```
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

In [45]:
n = np.ones ((5,5))
n[0::4, :]=0
n[:, 0::4]=0
print(n)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### Target 14
```
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]

In [46]:
o = np.zeros ((5,5))
o[2,:]=1
o[:,2]=1
print(o)

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### Target 15
```
[[1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]]

In [47]:
p = np.zeros((5,5))
for i in range(p.shape[0]):
    p[i,i]=1
    p[i,p.shape[0]-1-i]=1
print(p)

[[1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]


#### Target 16
```
[[0 0 0 0]
 [7 0 0 0]
 [0 7 0 0]
 [0 0 7 0]
 [0 0 0 7]]

In [48]:
q = np.eye(5,4,-1)
q[q!=0]=7
print(q)

[[0. 0. 0. 0.]
 [7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


#### Target 17
```
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]

In [49]:
r = np.arange(5)
r = np.vstack ((r, r+10, r+20, r+30))
print(r)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


#### Target 18
```
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]

In [50]:
s = np.linspace (0,1,num=5,dtype=float)
s = np.vstack((s,s,s))
print(s)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]


### Target 19
```
[[ 2 -1  0  0  0  0]
 [-1  2 -1  0  0  0]
 [ 0 -1  2 -1  0  0]
 [ 0  0 -1  2 -1  0]
 [ 0  0  0 -1  2 -1]
 [ 0  0  0  0 -1  2]]

In [51]:
top_left = np.ones((3,3))
top_right = np.full((3,3),2)
top = np.hstack ((top_left, top_right))
bottom = np.eye (3,6,k=3)
bottom[bottom!=0]=3
M = np.vstack ((top, bottom))
print(M)

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]


#### Target 20
```
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [0 0 0 3 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 3]]

In [52]:
top_left = np.ones((3,3))
top_right = np.full((3,3),2)
top = np.hstack ((top_left, top_right))
bottom = np.eye (3,6,k=3)
bottom[bottom!=0]=3
M = np.vstack ((top, bottom))
print(M)

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]
