## Set of array-construction exercises in NumPY
This notebook shows my solutions to array-construction exercises in NumPy.  
Markdown cells show the target matrices; code cells show my solution.

Constraints: 
- no for loops,
- only NumPy functions (zeros, ones, eye, diag, arange, reshape, linspace, tile, stack, minimum, slicing, indexing, ...)



In [4]:
import numpy as np

#### Target 01
```
[[1 2 3 4 5 6]]

In [62]:
import numpy as np
a=np.arange(1,7).reshape(1,-1)
print(a)

[[1 2 3 4 5 6]]


#### Target 02
```
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

In [34]:
b=np.arange(1,7)
b=b.reshape(-1,1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### Target 03
```
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]

In [35]:
c=np.eye(5,k=1)
print(c)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


#### Target 04
```
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

In [64]:
d = np.diag((1,2,3,4,5))
print(d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### Target 05
```
[[0 0 0 1]
 [0 0 2 0]
 [0 3 0 0]
 [4 0 0 0]]

In [69]:
e=np.fliplr(np.diag((1,2,3,4)))
print(e)

[[0 0 0 1]
 [0 0 2 0]
 [0 3 0 0]
 [4 0 0 0]]


#### Target 06
```
[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]

In [38]:
f = np.zeros((6,6))
f[0::2, 1::2]=1
f[1::2, 0::2]=1
print(f)

[[0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]]


#### Target 07
```
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]

In [72]:
g=np.zeros(5)
g=np.vstack((g,g+1,g+2,g+3,g+4))
print(g)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### Target 08
```
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

In [76]:
h=np.zeros((5,1))
h=np.hstack((h,h+1,h+2,h+3,h+4))
print(h)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### Target 09
```
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [78]:
j = np.arange (10,25).reshape((3,5))
print(j)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Target 10
```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

In [79]:
k = np.arange (0,18).reshape ((3,6))
print(k)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


#### Target 11
```
[[ 0  6 12]
 [ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]]

In [83]:
l = np.arange(18).reshape(6,3,order='F')
print(l)

[[ 0  6 12]
 [ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]]


#### Target 12
```
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

In [85]:
m = np.ones ((5,5))
m[1:-1,1:-1]=0
print(m)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Target 13
```
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

In [45]:
n = np.ones ((5,5))
n[0::4, :]=0
n[:, 0::4]=0
print(n)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### Target 14
```
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]

In [46]:
o = np.zeros ((5,5))
o[2,:]=1
o[:,2]=1
print(o)

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### Target 15
```
[[1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]]

In [89]:
p = np.eye (5,5)
p = np.clip(p + np.fliplr(p))
p[p>1]=1
print(p)

[[1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]


#### Target 16
```
[[0 0 0 0]
 [7 0 0 0]
 [0 7 0 0]
 [0 0 7 0]
 [0 0 0 7]]

In [93]:
q = 7*np.eye(5,4,-1)
print(q)

[[0. 0. 0. 0.]
 [7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


#### Target 17
```
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]

In [49]:
r = np.arange(5)
r = np.vstack ((r, r+10, r+20, r+30))
print(r)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


#### Target 18
```
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]

In [50]:
s = np.linspace (0,1,num=5,dtype=float)
s = np.vstack((s,s,s))
print(s)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]


### Target 19
```
[[ 2 -1  0  0  0  0]
 [-1  2 -1  0  0  0]
 [ 0 -1  2 -1  0  0]
 [ 0  0 -1  2 -1  0]
 [ 0  0  0 -1  2 -1]
 [ 0  0  0  0 -1  2]]

In [95]:
t = 2*np.eye(6,6) - np.eye(6,6,-1) - np.eye(6,6,+1)
print(t)

[[ 2. -1.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0. -1.  2.]]


#### Target 20
```
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [0 0 0 3 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 3]]

In [52]:
top_left = np.ones((3,3))
top_right = np.full((3,3),2)
top = np.hstack ((top_left, top_right))
bottom = np.eye (3,6,k=3)
bottom[bottom!=0]=3
M = np.vstack ((top, bottom))
print(M)

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]


#### Target 21
```
[[1 0 0 0 0 0]
 [1 1 0 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 1 0 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 1]]


In [162]:
i, j = np.indices ((6,6))
a[j-i<=0]=1
print(a)

[[1 0 0 0 0 0]
 [1 1 0 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 1 0 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 1]]


#### Target 22
```
[[6 5 4 3 4 5 6]
 [5 4 3 2 3 4 5]
 [4 3 2 1 2 3 4]
 [3 2 1 0 1 2 3]
 [4 3 2 1 2 3 4]
 [5 4 3 2 3 4 5]
 [6 5 4 3 4 5 6]]

In [100]:
e = np.array((3,2,1,0,1,2,3))
e = np.vstack((e+3, e+2, e+1, e, e+1, e+2, e+3))
print(e)

[[6 5 4 3 4 5 6]
 [5 4 3 2 3 4 5]
 [4 3 2 1 2 3 4]
 [3 2 1 0 1 2 3]
 [4 3 2 1 2 3 4]
 [5 4 3 2 3 4 5]
 [6 5 4 3 4 5 6]]


#### Target 23
```
[[ 0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7]
 [ 0  2  4  6  8 10 12 14]
 [ 0  3  6  9 12 15 18 21]
 [ 0  4  8 12 16 20 24 28]]


In [104]:
f = np.arange(1,8)
f = np.vstack ((0*f, 1*f, 2*f, 3*f, 4*f)) 
print(f)

[[ 0  0  0  0  0  0  0]
 [ 1  2  3  4  5  6  7]
 [ 2  4  6  8 10 12 14]
 [ 3  6  9 12 15 18 21]
 [ 4  8 12 16 20 24 28]]


#### Target 24
```
[[0 1 2 3 4 5]
 [1 0 1 2 3 4]
 [2 1 0 1 2 3]
 [3 2 1 0 1 2]
 [4 3 2 1 0 1]
 [5 4 3 2 1 0]]


In [164]:
i, j = np.indices((6,6))
g[i,j]=abs(i-j)
print(g)

[[0. 1. 2. 3. 4. 5.]
 [1. 0. 1. 2. 3. 4.]
 [2. 1. 0. 1. 2. 3.]
 [3. 2. 1. 0. 1. 2.]
 [4. 3. 2. 1. 0. 1.]
 [5. 4. 3. 2. 1. 0.]]


#### Target 25
```
[[0 0 1 1 0 0 1 1]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [1 1 0 0 1 1 0 0]]


In [141]:
h = np.zeros((2,2))
i = np.ones((2,2))
j = np.vstack(( np.hstack((h, i, h, i)), np.hstack((i, h, i, h))))
j = np.vstack(( j, j))
print(j)

[[0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0.]]


#### Target 26
```
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 2 2 2 1 0]
 [0 1 2 3 2 1 0]
 [0 1 2 2 2 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [175]:
i, j = np.indices((7,7))
k = np.minimum.reduce([i,j, 7-i, 7-j])
print(k)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1]
 [0 1 2 2 2 2 1]
 [0 1 2 3 3 2 1]
 [0 1 2 3 3 2 1]
 [0 1 2 2 2 2 1]
 [0 1 1 1 1 1 1]]


#### Target 27
```
[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


In [138]:
l = np.array((0,1,2))
l = np.tile(l, (6,3))
print(l)

# Alternative
#l = np.zeros((1,6)).reshape(-1,1)
#l = np.hstack ((l, l+1, l+2, l, l+1, l+2, l+3, l, l+1, l+2, l+3))
#print(l)

# Alternative #2
#l = np.array ((0,1,2))
#l = np.hstack ([l]*3)
#l = np.vstack ([l]*6)

[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


#### Target 28
```
[[0 0 0 0 0 0]
 [0 1 1 1 1 1]
 [0 1 2 2 2 2]
 [0 1 2 3 3 3]
 [0 1 2 3 4 4]
 [0 1 2 3 4 5]]

In [152]:
i, j = np.indices((6,6))
m = np.minimum(i,j)
print(m)

[[0 0 0 0 0 0]
 [0 1 1 1 1 1]
 [0 1 2 2 2 2]
 [0 1 2 3 3 3]
 [0 1 2 3 4 4]
 [0 1 2 3 4 5]]


#### Target 29
```
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]

In [169]:
i, j = np.indices ((5,5))
n[i,j] = j+i
print(n)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


#### Target 30
```
[[ 4 -1 -1  0  0  0]
 [-1  4 -1 -1  0  0]
 [-1 -1  4 -1 -1  0]
 [ 0 -1 -1  4 -1 -1]
 [ 0  0 -1 -1  4 -1]
 [ 0  0  0 -1 -1  4]]

In [171]:
o = 4*np.eye(6) - np.eye(6, k=-1) - np.eye(6, k=-2) - np.eye(6, k=1) - np.eye(6, k=2)
print(o)

[[ 4. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  4.]]


#### Target 31
```
[[0 1 2 3 4 5 6]
 [1 0 1 2 3 4 5]
 [2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3]
 [4 3 2 1 0 1 2]
 [5 4 3 2 1 0 1]
 [6 5 4 3 2 1 0]]

In [24]:
p = np.zeros((7,7))
for i in range(p.shape[0]):
    p += i*np.eye(p.shape[0], k=i)
    p += i*np.eye(p.shape[0], k=-i)
print(p)

[[0. 1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 2. 3. 4. 5.]
 [2. 1. 0. 1. 2. 3. 4.]
 [3. 2. 1. 0. 1. 2. 3.]
 [4. 3. 2. 1. 0. 1. 2.]
 [5. 4. 3. 2. 1. 0. 1.]
 [6. 5. 4. 3. 2. 1. 0.]]


#### Target 31
```
[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 2 2 2 2 1 0]
 [0 1 2 3 3 2 1 0]
 [0 1 2 3 3 2 1 0]
 [0 1 2 2 2 2 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]

In [19]:
a = np.zeros ((8,8))
i, j = np.indices(np.shape(a))
a[i,j] = np.minimum.reduce ([i, j, a.shape[0]-i-1, a.shape[1]-j-1])
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 2. 2. 1. 0.]
 [0. 1. 2. 3. 3. 2. 1. 0.]
 [0. 1. 2. 3. 3. 2. 1. 0.]
 [0. 1. 2. 2. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
